version: "3"

services:
  database:
    image: mysql
    container_name: dvpayments-database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: dvpayments
    ports:
      - '3306:3306'