name: Dvpayments
version: '${version}'
main: net.teamdvlpr.dvpayments.plugin.DvpaymentsPlugin
api-version: 1.19
authors: [izakdvlpr, ghostnicolas]
depend: [TitleAPI]
commands:
  login:
    aliases: ["logar"]
  register:
    aliases: ["registrar"]
  email:
    aliases: ["mail"]
  verify:
    aliases: ["verificar"]
  prime:
    aliases: ["celular"]